server:
  port: 8080 #当前服务节点端口
  contextPath: /
  servlet:
    encoding:
      force: true
      charset: UTF-8

spring:
  application:
    name: dataway-demo #当前应用的名称

  ################### DataSource Configuration ##########################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dataway?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: Passw0rd
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
      stat-view-servlet:
        login-username: admin
        login-password: druid
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1

# 启用 Dataway 功能（默认不启用）
HASOR_DATAQL_DATAWAY: true
# 开启 ui 管理功能（注意生产环境必须要设置为 false，否则会造成严重的生产安全事故）
HASOR_DATAQL_DATAWAY_ADMIN: true

# （可选）API工作路径
HASOR_DATAQL_DATAWAY_API_URL: /api/
# （可选）ui 的工作路径，只有开启 ui 管理功能后才有效
HASOR_DATAQL_DATAWAY_UI_URL: /interface-ui/


hasor:
  dataway:
    authorization:
      username: admin
      password: dataway

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
